### ISSUE TITLE
Awesome! .cursor needed?

### ISSUE THREAD

**Issue by mhulse** [beekman/Rainbow-Selection-Flux#1]
Hey, nice work!

This bit:

https://github.com/beekman/Rainbow-Selection-Flux/blob/7b556c8756a0ba121eb80721ce90c365c61c40bf/styles/rainbow-selection-flux.atom-text-editor.less#L7-L10

Is that needed?

Thanks for making this a package!

**Comment by beekman** [comment]
No, and sorry I didn't push the version I was working on where I'd already removed it. :)
