### ISSUE TITLE
mix-blend-mode: difference;

### ISSUE THREAD

**Issue by mhulse** [beekman/Rainbow-Selection-Flux#4]
I think this would be a cool addition down road. This would invert the color of selected text to the opposite of background of selection.

I wasn't able to get it to work though.

https://discuss.atom.io/t/change-color-of-selected-text/6245/9

Looks like a limitation of Atom:

https://github.com/atom/atom/issues/2886

Maybe they'll fix it one day?

**Comment by beekman** [comment]
Hope so, that would probably look awesome! Maybe we should close this until/if they do?

**Comment by mhulse** [comment]
> Hope so, that would probably look awesome! Maybe we should close this until/if they do?

Sure! :)
