### ISSUE TITLE
Requires Shadow DOM

### ISSUE THREAD

**Issue by beekman** [beekman/Rainbow-Selection-Flux#7]
Our effect is dependent on using the Shadow DOM. Eventually that will no longer be an option. @mhulse, do you have any idea how feasible is it to eventually get this working without Shadow DOM?

**Comment by mhulse** [comment]
Oh, shadow dom is going away?

**Comment by beekman** [comment]
Eventually.
<img width="436" alt="screen shot 2016-08-21 at 2 50 02 pm" src="https://cloud.githubusercontent.com/assets/563233/17839990/95e8b14a-67ae-11e6-87bc-d9887ea7275e.png">

**Comment by beekman** [comment]
Never mind, I misread the message, it turns out that eventually you won't be able to disable Shadow DOM at all, not that Shadow DOM will be going away.
